kind: Pod
apiVersion: v1
metadata:
  name: purrplingbot
spec:
  containers:
  - name: purrplingbot
    image: purrplingcat/purrplingbot:2.3.0
    ports:
    - containerPort: 9120
      hostPort: 9120
    env:
    - name: TZ
      value: Europe/Prague
    volumeMounts:
    - name: config
      mountPath: /data/config
    - name: localtime
      readOnly: true
      mountPath: /etc/localtime
    - name: timezone
      readOnly: true
      mountPath: /etc/timezone
  - name: purrplingbot-mongo
    image: mongo:4.4.4
    volumeMounts:
      - name: mongodata
        mountPath: /data/db
  volumes:
  - name: config
    hostPath:
      path: /var/lib/purrplingbot
  - name: localtime
    hostPath:
      path: /etc/localtime
  - name: timezone
    hostPath:
      path: /etc/timezone
  - name: mongodata
    hostPath: 
      path: /var/lib/purrplingbot/db
