"@imports":
  mumblebox: extras/mumblebox.yaml
  catsnack: extras/catsnack.yaml
  catnature: extras/catnature.yaml
  # cron: config/cron.yaml
cmdPrefix: "!"
pluginsDisabled: []
storage:
  file: config/storedb.json
  autosave: true
  autosaveInterval: 90
discord:
  token: MzIzMzk3MjU4MDgxFBn1MjAx.DB6raw.U4n_AdA-bGYKFTATc6ACFI2mnTA
admins:
- PurrplingCat
- CallMeFoxie
eventLogger:
  enabled: false
  loggingChannelID: '323516538378256395'
twitch:
  twitch_token: l3d809bfd3r20buu2d626ayyg83g64
  twitch_channel_name: purrplingcat
  twitch_channel_id: '125991922'
  twitch_stream_checker:
    enabled: true
    interval: 120
    announceChannelId: '323516538378256395'
twitchcord:
  username: purrplingbot
  password: oauth:3j98jl1efnoobmeb00tnlshw69ac9x
  twitchChannel: "#purrplingcat"
  discordChannelId: '323516538378256395'
  reconnectLimit: 64
announcer:
  antispam: true
  inactivity: 45m
  activityLinesThreshold: 1
  repeater:
    enabled: false
    expirePercentTime: 0.25
    handleWait: 2m
greetings:
  channelID: '323516538378256395'
  greetingMessage: Vítej mezi námi!
