actions:
  foobar: plugins/Cron/actions/foobar.js
plan:
  cron1:
    schedule: '1 * * * * *' # s m H D M E (* - represents any value of segment)
    action: sendMessage
    args:
      - '300515295821299714'
      - cron test
  cron2:
    format: DateTime
    schedule: '2017-09-27 12:04'
    action: sendMessage
    args:
      - '300515295821299714'
      - cron test DateTime
